version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: build
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: build
    volumes:
      - ./frontend:/app
    ports:
    - 5173:5173
    tty: true
    command: npm run dev
    env_file:
      - .env

  database:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env