version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: build
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: build
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    command: npm run dev
    env_file:
      - .env

  database:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env