version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: build
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 4000:4000
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: build
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
    - 5173:5173
    command: npm run dev