name: CI

on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1

      - name: Hello!
        run: echo "Hello from ${{github.workflow}} triggered by the ${{github.event_name}} done by ${{github.actor}}"

      - name: More and More
        env:
          JOB_CONTEXT: ${{toJson(job)}}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo Done!

      # - name: Install dependencies
      #   working-directory: ./backend
      #   run: npm install

      # - name: Run tests
      #   working-directory: ./backend
      #   run: npm run test:unit

  # backend-unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Node.js
  #       uses: actions/setup-node@v4
      
  #     - run: cd backend && npm i
        
  #     - name: Run tests
  #       run: npm run test:backend:unit

  # frontend-unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Node.js
  #       uses: actions/setup-node@v4
      
  #     - run: cd frontend && npm i
        
  #     - name: Run tests
  #       run: npm run test:frontend:unit

  # e2e-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Node.js
  #       uses: actions/setup-node@v4
      
  #     - run: npm i

  #     - uses: hoverkraft-tech/compose-action@v1.5.1
  #       with:
  #         compose-file: "./docker-compose.dev.yml"
  #       env:
  #         POSTGRES_USER: "postgres"
  #         POSTGRES_PASSWORD: "postgres"
  #         POSTGRES_DB: "mydb"
  #         DATABASE_URL: "postgresql://postgres:postgres@database:5432/mydb"
      
  #     - name: Run tests
  #       run: npm run test:e2e
