name: CI

on: [push]

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: cd backend && npm install
      - name: Run tests
        run: npm run test:backend:unit

  # integration-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/build
  #     - uses: ./.github/actions/docker-compose
  #     - name: Run tests
  #       run: npm run test:backend:int

  # e2e-tests:
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v3
    #   - uses: ./.github/actions/build
    #   - uses: ./.github/actions/docker-compose
    #   - name: Install Playwright
    #     run: cd e2e && npx playwright install --with-deps
    #   - run: cd e2e && npx playwright install
    #   - name: Run tests
    #     run: npm run test:e2e