name: CI

on: [push]

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3

      - uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: './docker-compose.dev.yml'
          service: backend
      - run: npm run test:unit:backend

  # integration-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/build
  #     - uses: ./.github/actions/docker-compose
  #     - name: Run tests
  #       run: npm run test:backend:int

  # e2e-tests:
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v3
    #   - uses: ./.github/actions/build
    #   - uses: ./.github/actions/docker-compose
    #   - name: Install Playwright
    #     run: cd e2e && npx playwright install --with-deps
    #   - run: cd e2e && npx playwright install
    #   - name: Run tests
    #     run: npm run test:e2e